version: "3.4"
services:
  nodejs:
    build: 
      context: .
    image: amakundu/nodejs-mysql-app
    networks:
      - frontend
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "30001:8005"
    container_name: moe-nodejs-app
networks:
  frontend: